### PR TITLE
Add benchmark suite for Luwra

### PR DESCRIPTION
**Pull request by vapourismo**
I've added a benchmark for Luwra.

Some of the binding frameworks did not work on my machine, therefore I could not test the entire benchmark suite.

### CODE REVIEW

**Comment by satoren** [comment]
thank you

**Comment by vapourismo** [comment]
I've updated the [luwra branch](https://github.com/vapourismo/lua_binding_benchmark/tree/luwra) even further, so that all benchmark tests are implemented.

If you could go ahead and merge these changes aswell, that would be awesome :heart_eyes:

**Comment by satoren** [comment]
Implement of table-chain is not correct.
It is global table called.

**Comment by vapourismo** [comment]
Good ol' copy-pasta. It is fixed now.

**Comment by satoren** [comment]
Thank you. it's merged.#6

**Pull request merged**
